spring:
  application:
    name:cloudBalance
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 38231
jwt:
    token-prefix: Bearer
    header: Authorization
    issuer: cloudBalance
    audience: cloudBalance
    secret: 9eF#Wm@Z!tGpLrXq3v8yBuCjDkQnShVm
    expiration: 900000

aws:
  region: ap-south-1

snowflake:
  account: YFYRZGG-BWB35436
  username: ro_user
  password: fRe$her@b00tc@mp2025
  warehouse: COMPUTE_WH
  database: aws
  schema: cost
